[build]
builder = 'nixpacks'
buildCommand = 'cd backend && npm install && cd ../frontend && npm install && npm run build && cd ..'

[deploy]
startCommand = 'cd backend && npm start'
healthcheckPath = '/'
healthcheckTimeout = 100

[nixpacks]
nodejs-version = '16.x'
