[build]
builder = 'nixpacks'
buildCommand = '''
  cd backend && npm install &&
  cd ../frontend && npm install && npm run build
'''

[deploy]
startCommand = '''
  cd backend && npm start &
  npx serve -s frontend/build -l 3000
'''
healthcheckPath = '/'
healthcheckTimeout = 100

[nixpacks]
nodejs-version = '16.x'
