[build]
# Use the default builder, Railway will handle this via Docker
builder = "docker"

[deploy]
# Start the backend and frontend concurrently using the start script
startCommand = "npm start"

# Optionally, specify environment variables here or in Railway's environment settings UI
