[build]
# Railway will automatically detect and build both the backend and frontend.
buildCommand = "npm install && npm run build"

[deploy]
# Start both the backend and frontend.
startCommand = "npm start"

# Specify the Node.js version if necessary.
[nixpacks]
nodejsVersion = "16.x"
