[build]
# Make sure these commands are explicitly Node.js-related and not Docker-related.
buildCommand = "npm install && npm run build"

[deploy]
# Ensure the start command is simple and straightforward, suitable for your Node.js app.
startCommand = '''
  cd backend && npm start &
  cd frontend && npx serve -s build -l 3000
'''

[nixpacks]
# Specify the Node.js version to ensure Nixpacks handles the project correctly.
nodejs-version = '16.x'
