[build]
builder = "NIXPACKS"
nixpacksPlan = {"providers":["nodejs", "python"]}

[deploy]
runtime = "V2"
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
