[build]
# Use the Dockerfile for building the project
builder = "docker"

# No custom build command needed since Dockerfile handles it

[deploy]
# No custom start command needed since Dockerfile handles it
